// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Get(arg1, arg2) {
  return window['go']['wailsconfigstore']['ConfigStore']['Get'](arg1, arg2);
}

export function Set(arg1, arg2) {
  return window['go']['wailsconfigstore']['ConfigStore']['Set'](arg1, arg2);
}
