// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wailsconfigstore} from '../models';

export function Get(arg1:string,arg2:string):Promise<wailsconfigstore.Config>;

export function Set(arg1:string,arg2:wailsconfigstore.Config):Promise<void>;
