// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GoCheckIsStartProject(arg1) {
  return window['go']['main']['App']['GoCheckIsStartProject'](arg1);
}

export function GoOpenWithPhpStorm(arg1, arg2) {
  return window['go']['main']['App']['GoOpenWithPhpStorm'](arg1, arg2);
}

export function GoSelectFolderDialog() {
  return window['go']['main']['App']['GoSelectFolderDialog']();
}

export function GoSendNotification(arg1, arg2) {
  return window['go']['main']['App']['GoSendNotification'](arg1, arg2);
}

export function GoStartProject(arg1, arg2) {
  return window['go']['main']['App']['GoStartProject'](arg1, arg2);
}

export function GoStopProject(arg1) {
  return window['go']['main']['App']['GoStopProject'](arg1);
}
