// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GoCheckIsStartProject(arg1:Array<string>):Promise<main.Response>;

export function GoOpenWithPhpStorm(arg1:string,arg2:string):Promise<main.Response>;

export function GoSelectFolderDialog():Promise<main.Response>;

export function GoSendNotification(arg1:string,arg2:string):Promise<main.Response>;

export function GoStartProject(arg1:string,arg2:string):Promise<main.Response>;

export function GoStopProject(arg1:string):Promise<main.Response>;
